version: '3'
services:

  dummy:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    links:
      - postgres_dummy
    volumes:
      - ./:/app
      - gem-volume:/usr/local/bundle
    command: "bundle exec rails server -b 0.0.0.0"
    user: ${CURRENT_UID}
    stdin_open: true
    tty: true

  webpack-watcher:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      RAILS_ENV: development
    volumes:
      - ./:/app
      - gem-volume:/usr/local/bundle
    command: "sh -c 'cd spec/dummy && ./bin/webpack --watch'"
    user: ${CURRENT_UID}

  test:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    environment:
      RAILS_ENV: test
    links:
      - postgres_test
    ports:
      - "33123:33123"
    volumes:
      - ./:/app
      - gem-volume:/usr/local/bundle
    command: "bundle exec rspec spec/test"
    user: ${CURRENT_UID}



  postgres_dummy:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dummy
    volumes:
      - dummy-data-volume:/var/lib/postgresql/data

  postgres_test_base: &postgres_test_base
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test

  postgres_test:
    <<: *postgres_test_base

volumes:
  test-data-volume:
  dummy-data-volume:
  gem-volume:
